import {CENTER, TOP, BOTTOM} from './positions';
import {SUCCESS, WARNING, ERROR, INFO} from './messageTypes';
import {width, height, fontSize} from './dimentions';
import {
  success,
  success_light,
  warning,
  warning_light,
  error,
  error_light,
  success_dark,
  warning_dark,
  error_dark,
  info_dark,
  white,
  black,
  ColorsMap,
  success_border,
  warning_border,
  error_border,
  info_border,
  success_medium,
  warning_medium,
  error_medium,
  info_medium,
  AlertStyleMap,
  PositionStyleMap,
  IconsMap,
  gray_dark,
  gray_light,
  IconsColorMap,
} from './colors';
import {Icons} from './icons';
export {
  CENTER,
  TOP,
  BOTTOM,
  SUCCESS,
  WARNING,
  ERROR,
  INFO,
  width,
  height,
  success,
  success_light,
  warning,
  warning_light,
  error,
  error_light,
  success_dark,
  warning_dark,
  error_dark,
  info_dark,
  white,
  black,
  ColorsMap,
  success_border,
  warning_border,
  error_border,
  info_border,
  fontSize,
  success_medium,
  warning_medium,
  error_medium,
  info_medium,
  Icons,
  AlertStyleMap,
  PositionStyleMap,
  IconsMap,
  gray_dark,
  gray_light,
  IconsColorMap,
};
